from django.core.management.base import BaseCommand

from core.models import Maladie


class Command(BaseCommand):
    help = "Enregistre automatiquement une liste de maladies dans la base de données"

    DISEASES = [
        {"nom": "Grippe", "categorie": "infectieuse", "description": "Infection virale fréquente", "gravite": "leger"},
        {"nom": "Diabète de type 2", "categorie": "metabolique", "description": "Dérèglement du métabolisme du glucose", "gravite": "modere"},
        {"nom": "Hypertension artérielle", "categorie": "cardiovasculaire", "description": "Pression artérielle élevée", "gravite": "modere"},
        {"nom": "Asthme", "categorie": "respiratoire", "description": "Maladie inflammatoire des voies respiratoires", "gravite": "modere"},
        {"nom": "Cancer du sein", "categorie": "cancer", "description": "Tumeur maligne au niveau du sein", "gravite": "grave"},
        {"nom": "Sclérose en plaques", "categorie": "neurologique", "description": "Maladie auto-immune affectant le système nerveux central", "gravite": "grave"},
        {"nom": "Lupus", "categorie": "autoimmune", "description": "Maladie auto-immune systémique", "gravite": "grave"},
        {"nom": "Alzheimer", "categorie": "neurologique", "description": "Maladie neurodégénérative entraînant une perte de mémoire", "gravite": "grave"},
        {"nom": "Dépression", "categorie": "psychiatrique", "description": "Trouble de l'humeur caractérisé par une tristesse persistante", "gravite": "modere"},
        {"nom": "Arthrite rhumatoïde", "categorie": "musculosquelettique", "description": "Maladie inflammatoire des articulations", "gravite": "modere"},
        {"nom": "Grippe", "categorie": "infectieuse", "description": "Infection virale fréquente", "gravite": "leger"},
        {"nom": "COVID-19", "categorie": "infectieuse", "description": "Maladie respiratoire causée par le SARS-CoV-2",
         "gravite": "modere"},
        {"nom": "Tuberculose", "categorie": "infectieuse",
         "description": "Infection bactérienne affectant principalement les poumons", "gravite": "grave"},
        {"nom": "Hépatite B", "categorie": "infectieuse", "description": "Infection virale chronique touchant le foie",
         "gravite": "modere"},
        {"nom": "Rougeole", "categorie": "infectieuse", "description": "Maladie virale hautement contagieuse",
         "gravite": "modere"},
        {"nom": "Paludisme", "categorie": "infectieuse",
         "description": "Maladie parasitaire transmise par les moustiques", "gravite": "grave"},
        {"nom": "VIH/SIDA", "categorie": "infectieuse",
         "description": "Infection virale affaiblissant le système immunitaire", "gravite": "grave"},
        {"nom": "Fièvre typhoïde", "categorie": "infectieuse",
         "description": "Maladie bactérienne due à Salmonella typhi", "gravite": "modere"},
        {"nom": "Ebola", "categorie": "infectieuse", "description": "Fièvre hémorragique sévère causée par un virus",
         "gravite": "grave"},
        {"nom": "Choléra", "categorie": "infectieuse",
         "description": "Infection bactérienne provoquant des diarrhées sévères", "gravite": "grave"},
        {"nom": "Varicelle", "categorie": "infectieuse", "description": "Infection virale fréquente chez les enfants",
         "gravite": "leger"},
        {"nom": "Zika", "categorie": "infectieuse", "description": "Maladie virale transmise par les moustiques",
         "gravite": "leger"},
        {"nom": "Dengue", "categorie": "infectieuse", "description": "Fièvre virale transmise par les moustiques",
         "gravite": "modere"},
        {"nom": "Tétanos", "categorie": "infectieuse",
         "description": "Infection bactérienne grave causant des spasmes musculaires", "gravite": "grave"},
        {"nom": "Rage", "categorie": "infectieuse",
         "description": "Maladie virale fatale transmise par la salive d'animaux infectés", "gravite": "grave"},
        {"nom": "Méningite bactérienne", "categorie": "infectieuse",
         "description": "Inflammation des méninges causée par des bactéries", "gravite": "grave"},
        {"nom": "Hépatite A", "categorie": "infectieuse",
         "description": "Infection virale hépatique transmise par l'eau ou les aliments contaminés",
         "gravite": "modere"},
        {"nom": "Hépatite C", "categorie": "infectieuse", "description": "Infection virale hépatique souvent chronique",
         "gravite": "grave"},
        {"nom": "Fièvre jaune", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les moustiques, causant une jaunisse sévère", "gravite": "grave"},
        {"nom": "Lèpre", "categorie": "infectieuse",
         "description": "Maladie bactérienne chronique affectant la peau et les nerfs", "gravite": "modere"},
        {"nom": "Syphilis", "categorie": "infectieuse", "description": "Maladie bactérienne transmise sexuellement",
         "gravite": "modere"},
        {"nom": "Gonorrhée", "categorie": "infectieuse",
         "description": "Infection bactérienne transmissible sexuellement", "gravite": "modere"},
        {"nom": "Candidose invasive", "categorie": "infectieuse", "description": "Infection fongique grave",
         "gravite": "grave"},
        {"nom": "Peste", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par les puces, parfois mortelle", "gravite": "grave"},
        {"nom": "Fièvre de Lassa", "categorie": "infectieuse",
         "description": "Fièvre hémorragique virale endémique en Afrique de l'Ouest", "gravite": "grave"},
        {"nom": "Brucellose", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par des animaux infectés", "gravite": "modere"},
        {"nom": "Anthrax", "categorie": "infectieuse",
         "description": "Infection bactérienne grave, souvent liée à des spores dans l'environnement",
         "gravite": "grave"},
        {"nom": "Listeriose", "categorie": "infectieuse",
         "description": "Infection bactérienne due à la consommation d'aliments contaminés", "gravite": "grave"},
        {"nom": "Fièvre Q", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par les animaux", "gravite": "modere"},
        {"nom": "Encéphalite à tiques", "categorie": "infectieuse",
         "description": "Infection virale transmise par les tiques", "gravite": "modere"},
        {"nom": "Poliomyélite", "categorie": "infectieuse",
         "description": "Infection virale pouvant causer une paralysie", "gravite": "grave"},
        {"nom": "Leptospirose", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par l'eau contaminée", "gravite": "modere"},
        {"nom": "Fièvre hémorragique de Marburg", "categorie": "infectieuse",
         "description": "Maladie virale grave similaire à Ebola", "gravite": "grave"},
        {"nom": "Trypanosomiase africaine", "categorie": "infectieuse",
         "description": "Maladie parasitaire transmise par la mouche tsé-tsé", "gravite": "grave"},
        {"nom": "Grippe", "categorie": "infectieuse", "description": "Infection virale fréquente", "gravite": "leger"},
        {"nom": "Fièvre boutonneuse méditerranéenne", "categorie": "infectieuse",
         "description": "Infection transmise par les tiques, causée par Rickettsia conorii", "gravite": "modere"},
        {"nom": "Actinomycose", "categorie": "infectieuse",
         "description": "Infection bactérienne chronique causée par Actinomyces israelii", "gravite": "grave"},
        {"nom": "Botulisme", "categorie": "infectieuse",
         "description": "Intoxication alimentaire grave causée par Clostridium botulinum", "gravite": "grave"},
        {"nom": "Erisipèle", "categorie": "infectieuse",
         "description": "Infection bactérienne de la peau due à Streptococcus pyogenes", "gravite": "modere"},
        {"nom": "Fièvre des tranchées", "categorie": "infectieuse",
         "description": "Maladie causée par Bartonella quintana, transmise par les poux", "gravite": "modere"},
        {"nom": "Nocardiose", "categorie": "infectieuse",
         "description": "Maladie bactérienne due à Nocardia spp., affectant souvent les poumons", "gravite": "grave"},
        {"nom": "Tularemie", "categorie": "infectieuse",
         "description": "Infection zoonotique causée par Francisella tularensis", "gravite": "modere"},
        {"nom": "Mycoplasmose pulmonaire", "categorie": "infectieuse",
         "description": "Infection respiratoire causée par Mycoplasma pneumoniae", "gravite": "modere"},
        {"nom": "Legionellose", "categorie": "infectieuse",
         "description": "Infection bactérienne des poumons causée par Legionella pneumophila", "gravite": "grave"},
        {"nom": "Shigellose", "categorie": "infectieuse", "description": "Maladie diarrhéique causée par Shigella spp.",
         "gravite": "grave"},
        {"nom": "Typhus épidémique", "categorie": "infectieuse",
         "description": "Infection causée par Rickettsia prowazekii", "gravite": "grave"},
        {"nom": "Paratyphoïde", "categorie": "infectieuse",
         "description": "Infection bactérienne similaire à la fièvre typhoïde, causée par Salmonella paratyphi",
         "gravite": "modere"},
        {"nom": "Yersiniose", "categorie": "infectieuse",
         "description": "Maladie intestinale causée par Yersinia enterocolitica", "gravite": "modere"},
        {"nom": "Maladie de Lyme", "categorie": "infectieuse",
         "description": "Infection transmise par les tiques, causée par Borrelia burgdorferi", "gravite": "modere"},
        {"nom": "Maladie des griffes du chat", "categorie": "infectieuse",
         "description": "Infection causée par Bartonella henselae", "gravite": "leger"},
        {"nom": "Pasteurellose", "categorie": "infectieuse",
         "description": "Infection transmise par des morsures ou griffures d'animaux, causée par Pasteurella multocida",
         "gravite": "modere"},
        {"nom": "Mélioïdose", "categorie": "infectieuse", "description": "Maladie causée par Burkholderia pseudomallei",
         "gravite": "grave"},
        {"nom": "Fièvre pourprée des montagnes Rocheuses", "categorie": "infectieuse",
         "description": "Infection causée par Rickettsia rickettsii", "gravite": "grave"},
        {"nom": "Chlamydiose respiratoire", "categorie": "infectieuse",
         "description": "Maladie due à Chlamydia pneumoniae", "gravite": "modere"},
        {"nom": "Hantavirus", "categorie": "infectieuse",
         "description": "Infections virales causant des syndromes pulmonaires ou rénaux", "gravite": "grave"},
        {"nom": "Roséole", "categorie": "infectieuse",
         "description": "Maladie virale bénigne chez l’enfant causée par le virus de l'herpès humain 6 ou 7",
         "gravite": "leger"},
        {"nom": "Herpès labial", "categorie": "infectieuse",
         "description": "Causé par le virus de l'herpès simplex (HSV-1)", "gravite": "leger"},
        {"nom": "Zona", "categorie": "infectieuse", "description": "Réactivation du virus varicelle-zona (VZV)",
         "gravite": "modere"},
        {"nom": "Virus de l'encéphalite japonaise", "categorie": "infectieuse",
         "description": "Infection transmise par les moustiques", "gravite": "grave"},
        {"nom": "Virus Chikungunya", "categorie": "infectieuse",
         "description": "Transmis par les moustiques, causant des douleurs articulaires sévères", "gravite": "modere"},
        {"nom": "Blastomycose", "categorie": "infectieuse", "description": "Infection due à Blastomyces dermatitidis",
         "gravite": "grave"},
        {"nom": "Coccidioïdomycose", "categorie": "infectieuse",
         "description": "Infection causée par Coccidioides spp.", "gravite": "grave"},
        {"nom": "Tinea corporis", "categorie": "infectieuse", "description": "Infection fongique affectant la peau",
         "gravite": "modere"},
        {"nom": "Schistosomiase", "categorie": "infectieuse",
         "description": "Infection parasitaire due à des vers plats du genre Schistosoma", "gravite": "grave"},
        {"nom": "Filariose lymphatique", "categorie": "infectieuse",
         "description": "Maladie transmise par les moustiques, causée par Wuchereria bancrofti", "gravite": "modere"},
        {"nom": "Amibiase", "categorie": "infectieuse",
         "description": "Infection intestinale due à l'amibe Entamoeba histolytica", "gravite": "modere"},
        {"nom": "Leishmaniose viscérale", "categorie": "infectieuse",
         "description": "Infection parasitaire transmise par les phlébotomes", "gravite": "grave"},
        {"nom": "Leishmaniose cutanée", "categorie": "infectieuse",
         "description": "Forme cutanée de la leishmaniose causant des ulcères", "gravite": "modere"},
        {"nom": "Dracunculose", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Dracunculus medinensis", "gravite": "modere"},
        {"nom": "Echinococcose", "categorie": "infectieuse",
         "description": "Maladie parasitaire causée par Echinococcus granulosus", "gravite": "grave"},
        {"nom": "Toxoplasmose", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Toxoplasma gondii", "gravite": "modere"},
        {"nom": "Trypanosomiase américaine (Maladie de Chagas)", "categorie": "infectieuse",
         "description": "Maladie parasitaire transmise par des insectes, causée par Trypanosoma cruzi",
         "gravite": "grave"},
        {"nom": "Ascaridiose", "categorie": "infectieuse",
         "description": "Infection intestinale due au ver Ascaris lumbricoides", "gravite": "leger"},
        {"nom": "Trichinellose", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par la consommation de viande contaminée par Trichinella spiralis",
         "gravite": "modere"},
        {"nom": "Onchocercose", "categorie": "infectieuse",
         "description": "Maladie parasitaire causée par Onchocerca volvulus, entraînant une cécité des rivières",
         "gravite": "grave"},
        {"nom": "Histoplasmose", "categorie": "infectieuse",
         "description": "Infection pulmonaire causée par le champignon Histoplasma capsulatum", "gravite": "grave"},
        {"nom": "Cryptococcose", "categorie": "infectieuse",
         "description": "Infection fongique grave causée par Cryptococcus neoformans", "gravite": "grave"},
        {"nom": "Pneumocystose", "categorie": "infectieuse",
         "description": "Infection pulmonaire grave causée par Pneumocystis jirovecii", "gravite": "grave"},
        {"nom": "Mucormycose", "categorie": "infectieuse",
         "description": "Infection fongique grave due à des champignons du genre Mucorales", "gravite": "grave"},
        {"nom": "Fasciolose hépatique", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Fasciola hepatica", "gravite": "modere"},
        {"nom": "Giardiase", "categorie": "infectieuse",
         "description": "Infection intestinale causée par Giardia lamblia", "gravite": "leger"},
        {"nom": "Balantidiose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par Balantidium coli", "gravite": "modere"},
        {"nom": "Paracoccidioïdomycose", "categorie": "infectieuse",
         "description": "Infection fongique rare causée par Paracoccidioides brasiliensis", "gravite": "grave"},
        {"nom": "Candidose cutanée", "categorie": "infectieuse",
         "description": "Infection fongique touchant la peau et les muqueuses", "gravite": "modere"},
        {"nom": "Anguillulose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par le ver Strongyloides stercoralis", "gravite": "grave"},
        {"nom": "Chikungunya", "categorie": "infectieuse",
         "description": "Fièvre virale transmise par les moustiques, causant des douleurs articulaires",
         "gravite": "modere"},
        {"nom": "Hépatite E", "categorie": "infectieuse",
         "description": "Infection virale hépatique transmise par de l'eau contaminée", "gravite": "modere"},
        {"nom": "Fièvre catarrhale ovine (Blue tongue)", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les insectes piqueurs", "gravite": "modere"},
        {"nom": "Fièvre de la Vallée du Rift", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les moustiques, touchant humains et animaux", "gravite": "grave"},
        {"nom": "Encéphalite à Saint-Louis", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques", "gravite": "grave"},
        {"nom": "Ornithose", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par des oiseaux, causée par Chlamydia psittaci",
         "gravite": "modere"},
        {"nom": "Listeriose alimentaire", "categorie": "infectieuse",
         "description": "Infection causée par la consommation d'aliments contaminés par Listeria monocytogenes",
         "gravite": "grave"},
        {"nom": "Brucellose humaine", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par le lait non pasteurisé", "gravite": "modere"},
        {"nom": "Psittacose", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par les perroquets et autres oiseaux", "gravite": "modere"},
        {"nom": "Mycétome", "categorie": "infectieuse",
         "description": "Infection fongique chronique des tissus sous-cutanés", "gravite": "grave"},
        {"nom": "Fièvre de la dengue hémorragique", "categorie": "infectieuse",
         "description": "Forme grave de la dengue causant des hémorragies", "gravite": "grave"},
        {"nom": "Zoonose de Campylobacter", "categorie": "infectieuse",
         "description": "Infection intestinale causée par Campylobacter spp.", "gravite": "modere"},
        {"nom": "Maladie de Whipple", "categorie": "infectieuse",
         "description": "Infection bactérienne rare affectant principalement l'intestin grêle", "gravite": "grave"},
        {"nom": "Fièvre de l'Ouest du Nil", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques, causant des symptômes neurologiques",
         "gravite": "grave"},
        {"nom": "Virus de Marburg", "categorie": "infectieuse",
         "description": "Fièvre hémorragique grave similaire à Ebola", "gravite": "grave"},
        {"nom": "Tularémie ulcéreuse", "categorie": "infectieuse",
         "description": "Forme ulcérative de la tularémie causée par Francisella tularensis", "gravite": "modere"},
        {"nom": "Méningococcémie", "categorie": "infectieuse",
         "description": "Infection bactérienne grave causée par Neisseria meningitidis", "gravite": "grave"},
        {"nom": "Anaplasmose humaine", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par les tiques", "gravite": "modere"},
        {"nom": "Fièvre récurrente à poux", "categorie": "infectieuse",
         "description": "Infection bactérienne causée par Borrelia recurrentis", "gravite": "modere"},
        {"nom": "Fièvre récurrente à tiques", "categorie": "infectieuse",
         "description": "Maladie causée par des bactéries Borrelia spp., transmise par les tiques",
         "gravite": "modere"},
        {"nom": "Phtiriase", "categorie": "infectieuse", "description": "Infestation parasitaire par les poux du pubis",
         "gravite": "leger"},
        {"nom": "Scarlatine", "categorie": "infectieuse",
         "description": "Infection bactérienne causée par Streptococcus pyogenes, associée à une éruption cutanée",
         "gravite": "modere"},
        {"nom": "Rickettsiose à tiques", "categorie": "infectieuse",
         "description": "Infection transmise par les tiques, causée par des bactéries du genre Rickettsia",
         "gravite": "modere"},
        {"nom": "Helicobacter pylori gastrite", "categorie": "infectieuse",
         "description": "Infection de l'estomac par Helicobacter pylori", "gravite": "modere"},
        {"nom": "Cryptosporidiose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par le parasite Cryptosporidium", "gravite": "leger"},
        {"nom": "Virus de l'encéphalite de Powassan", "categorie": "infectieuse",
         "description": "Infection virale transmise par les tiques, causant des symptômes neurologiques",
         "gravite": "grave"},
        {"nom": "Ulcère de Buruli", "categorie": "infectieuse",
         "description": "Infection bactérienne de la peau causée par Mycobacterium ulcerans", "gravite": "modere"},
        {"nom": "Fièvre phlébotomique", "categorie": "infectieuse",
         "description": "Fièvre virale transmise par les phlébotomes", "gravite": "leger"},
        {"nom": "Encéphalite de Californie", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques", "gravite": "grave"},
        {"nom": "Fièvre boutonneuse africaine", "categorie": "infectieuse",
         "description": "Infection causée par Rickettsia africae, transmise par les tiques", "gravite": "modere"},
        {"nom": "Diphyllobothriose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par le ver Diphyllobothrium latum", "gravite": "modere"},
        {"nom": "Cysticercose", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Taenia solium", "gravite": "grave"},
        {"nom": "Échinostome", "categorie": "infectieuse",
         "description": "Infection intestinale causée par des vers plats du genre Echinostoma", "gravite": "modere"},
        {"nom": "Paragonimose", "categorie": "infectieuse",
         "description": "Infection pulmonaire causée par le parasite Paragonimus", "gravite": "modere"},
        {"nom": "Loase", "categorie": "infectieuse",
         "description": "Infection parasitaire due à Loa loa, transmise par des mouches", "gravite": "modere"},
        {"nom": "Stongyloidose disséminée", "categorie": "infectieuse",
         "description": "Forme grave d'infection par Strongyloides stercoralis", "gravite": "grave"},
        {"nom": "Rhinosporidiose", "categorie": "infectieuse",
         "description": "Infection fongique des muqueuses causée par Rhinosporidium seeberi", "gravite": "modere"},
        {"nom": "Hépatozoonose", "categorie": "infectieuse",
         "description": "Infection parasitaire rare causée par Hépatozoon", "gravite": "modere"},
        {"nom": "Mycétome bactérien", "categorie": "infectieuse",
         "description": "Infection bactérienne chronique des tissus sous-cutanés", "gravite": "grave"},
        {"nom": "Borréliose de Lyme tardive", "categorie": "infectieuse",
         "description": "Forme chronique de la maladie de Lyme causée par Borrelia burgdorferi", "gravite": "grave"},
        {"nom": "Blastomycose pulmonaire", "categorie": "infectieuse",
         "description": "Infection fongique touchant principalement les poumons", "gravite": "grave"},
        {"nom": "Fièvre de la Vallée du Rift hémorragique", "categorie": "infectieuse",
         "description": "Forme grave de la fièvre de la Vallée du Rift causant des hémorragies", "gravite": "grave"},
        {"nom": "Infections par les hantavirus", "categorie": "infectieuse",
         "description": "Syndrome pulmonaire grave causé par l'inhalation d'excréments de rongeurs infectés",
         "gravite": "grave"},
        {"nom": "Méningo-encéphalite amibienne primaire", "categorie": "infectieuse",
         "description": "Infection cérébrale rare causée par Naegleria fowleri", "gravite": "grave"},
        {"nom": "Anguillulose disséminée", "categorie": "infectieuse",
         "description": "Forme sévère d'infection par Strongyloides stercoralis", "gravite": "grave"},
        {"nom": "Rage paralytique", "categorie": "infectieuse",
         "description": "Forme paralytique de la rage causée par le virus rabique", "gravite": "grave"},
        {"nom": "Coccidioïdomycose disséminée", "categorie": "infectieuse",
         "description": "Forme sévère de coccidioïdomycose affectant plusieurs organes", "gravite": "grave"},
        {"nom": "Histoplasmose disséminée", "categorie": "infectieuse",
         "description": "Forme grave de l'infection par Histoplasma capsulatum", "gravite": "grave"},
        {"nom": "Fièvre typhoïde chronique", "categorie": "infectieuse",
         "description": "Portage chronique de Salmonella typhi dans la vésicule biliaire", "gravite": "modere"},
        {"nom": "Ornithose sévère", "categorie": "infectieuse",
         "description": "Forme grave d'infection par Chlamydia psittaci", "gravite": "grave"},
        {"nom": "Fièvre puerpérale", "categorie": "infectieuse",
         "description": "Infection bactérienne post-partum, souvent due à Streptococcus pyogenes", "gravite": "grave"},
        {"nom": "Tuberculose extrapulmonaire", "categorie": "infectieuse",
         "description": "Forme de tuberculose affectant d'autres organes que les poumons", "gravite": "grave"},
        {"nom": "Fièvre des marais", "categorie": "infectieuse",
         "description": "Infection bactérienne transmise par l'eau contaminée", "gravite": "modere"},
        {"nom": "Paratyphoïde chronique", "categorie": "infectieuse",
         "description": "Portage chronique de Salmonella paratyphi", "gravite": "modere"},
        {"nom": "Hépatite virale aiguë D", "categorie": "infectieuse",
         "description": "Infection du foie causée par le virus de l'hépatite D, nécessitant une co-infection par le virus de l'hépatite B",
         "gravite": "grave"},
        {"nom": "Hépatite virale aiguë E", "categorie": "infectieuse",
         "description": "Forme aiguë d'hépatite causée par le virus de l'hépatite E", "gravite": "modere"},
        {"nom": "Strongyloïdose chronique", "categorie": "infectieuse",
         "description": "Forme bénigne mais prolongée de l'infection par Strongyloides stercoralis",
         "gravite": "modere"},
        {"nom": "Fièvre de l'encéphalite transmise par les tiques", "categorie": "infectieuse",
         "description": "Forme neurologique de l'infection virale transmise par les tiques", "gravite": "grave"},
        {"nom": "Encéphalite virale japonaise sévère", "categorie": "infectieuse",
         "description": "Forme grave de l'encéphalite japonaise causée par un flavivirus", "gravite": "grave"},
        {"nom": "Chlamydiose urogénitale", "categorie": "infectieuse",
         "description": "Infection bactérienne des voies génitales causée par Chlamydia trachomatis",
         "gravite": "modere"},
        {"nom": "Pneumonie virale COVID-19", "categorie": "infectieuse",
         "description": "Complication pulmonaire grave due à une infection par le SARS-CoV-2", "gravite": "grave"},
        {"nom": "Fièvre paratyphoïde sévère", "categorie": "infectieuse",
         "description": "Forme grave de paratyphoïde causée par Salmonella paratyphi", "gravite": "grave"},
        {"nom": "Schistosomiase intestinale", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Schistosoma mansoni", "gravite": "modere"},
        {"nom": "Schistosomiase urinaire", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Schistosoma haematobium", "gravite": "modere"},
        {"nom": "Mycétome eumycotique", "categorie": "infectieuse",
         "description": "Infection fongique chronique des tissus sous-cutanés", "gravite": "grave"},
        {"nom": "Urétrite à Mycoplasma genitalium", "categorie": "infectieuse",
         "description": "Infection sexuellement transmissible causée par Mycoplasma genitalium", "gravite": "modere"},
        {"nom": "Vaginose bactérienne", "categorie": "infectieuse",
         "description": "Déséquilibre bactérien du microbiote vaginal", "gravite": "leger"},
        {"nom": "Trichomonase", "categorie": "infectieuse",
         "description": "Infection sexuellement transmissible causée par Trichomonas vaginalis", "gravite": "modere"},
        {"nom": "Maladie de Katayama", "categorie": "infectieuse", "description": "Forme aiguë de la schistosomiase",
         "gravite": "grave"},
        {"nom": "Fièvre hémorragique bolivienne", "categorie": "infectieuse",
         "description": "Maladie virale grave causée par le virus Machupo", "gravite": "grave"},
        {"nom": "Fièvre de Junin", "categorie": "infectieuse",
         "description": "Fièvre hémorragique causée par le virus Junin en Amérique du Sud", "gravite": "grave"},
        {"nom": "Fièvre hémorragique d'Argentine", "categorie": "infectieuse",
         "description": "Maladie virale grave causée par un arenavirus", "gravite": "grave"},
        {"nom": "Fièvre hémorragique de Crimée-Congo", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les tiques", "gravite": "grave"},
        {"nom": "Anguillulose asymptomatique", "categorie": "infectieuse",
         "description": "Infection bénigne par Strongyloides stercoralis", "gravite": "leger"},
        {"nom": "Bartonellose", "categorie": "infectieuse",
         "description": "Infection bactérienne causée par Bartonella bacilliformis", "gravite": "grave"},
        {"nom": "Helminthiase multiple", "categorie": "infectieuse",
         "description": "Infection simultanée par plusieurs vers parasites", "gravite": "modere"},
        {"nom": "Infection à virus Hendra", "categorie": "infectieuse",
         "description": "Maladie zoonotique grave transmise par les chauves-souris", "gravite": "grave"},
        {"nom": "Infection à virus Nipah", "categorie": "infectieuse",
         "description": "Maladie virale grave transmise par les chauves-souris frugivores", "gravite": "grave"},
        {"nom": "Strongyloidose cutanée", "categorie": "infectieuse",
         "description": "Infection cutanée due à Strongyloides stercoralis", "gravite": "modere"},
        {"nom": "Fasciolopsiose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par Fasciolopsis buski", "gravite": "modere"},
        {"nom": "Filariose loiasis", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Loa loa", "gravite": "modere"},
        {"nom": "Cystoisosporose", "categorie": "infectieuse",
         "description": "Infection intestinale due à Cystoisospora belli", "gravite": "modere"},
        {"nom": "Cryptococcose pulmonaire", "categorie": "infectieuse",
         "description": "Infection pulmonaire causée par Cryptococcus neoformans", "gravite": "grave"},
        {"nom": "Infection à virus Mayaro", "categorie": "infectieuse",
         "description": "Fièvre virale transmise par les moustiques", "gravite": "modere"},
        {"nom": "Fièvre des sables de l'Afrique de l'Ouest", "categorie": "infectieuse",
         "description": "Fièvre virale transmise par les rongeurs", "gravite": "grave"},
        {"nom": "Blastomycose disséminée", "categorie": "infectieuse",
         "description": "Forme grave de blastomycose touchant plusieurs organes", "gravite": "grave"},
        {"nom": "Pythiose", "categorie": "infectieuse",
         "description": "Infection fongique rare touchant la peau ou les organes internes", "gravite": "grave"},
        {"nom": "Cholécystite aiguë bactérienne", "categorie": "infectieuse",
         "description": "Infection bactérienne de la vésicule biliaire", "gravite": "grave"},
        {"nom": "Toxocariose", "categorie": "infectieuse",
         "description": "Infection parasitaire causée par Toxocara canis ou Toxocara cati", "gravite": "modere"},
        {"nom": "Rhinite allergique infectieuse", "categorie": "infectieuse",
         "description": "Infection nasale causée par des allergènes et des agents pathogènes", "gravite": "leger"},
        {"nom": "Infection invasive à Aspergillus", "categorie": "infectieuse",
         "description": "Infection grave due au champignon Aspergillus", "gravite": "grave"},
        {"nom": "Dermatophytose étendue", "categorie": "infectieuse",
         "description": "Infection cutanée grave due aux dermatophytes", "gravite": "modere"},
        {"nom": "Trichomonose intestinale", "categorie": "infectieuse",
         "description": "Infection rare de l'intestin par Trichomonas", "gravite": "modere"},
        {"nom": "Fièvre à virus Chapare", "categorie": "infectieuse",
         "description": "Fièvre hémorragique rare causée par un arenavirus", "gravite": "grave"},
        {"nom": "Fièvre de la forêt de Kyasanur", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les tiques en Inde", "gravite": "grave"},
        {"nom": "Infection par Coxiella burnetii", "categorie": "infectieuse", "description": "Cause de la fièvre Q",
         "gravite": "modere"},
        {"nom": "Encéphalite équine de l'Est", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques", "gravite": "grave"},
        {"nom": "Encéphalite équine de l'Ouest", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques", "gravite": "grave"},
        {"nom": "Encéphalite équine vénézuélienne", "categorie": "infectieuse",
         "description": "Infection virale transmise par les moustiques en Amérique du Sud", "gravite": "grave"},
        {"nom": "Fièvre de Oroya", "categorie": "infectieuse",
         "description": "Phase aiguë de la bartonellose causée par Bartonella bacilliformis", "gravite": "grave"},
        {"nom": "Fièvre des tranchées", "categorie": "infectieuse",
         "description": "Infection bactérienne causée par Bartonella quintana", "gravite": "modere"},
        {"nom": "Epidermophytose", "categorie": "infectieuse",
         "description": "Infection fongique superficielle de la peau", "gravite": "leger"},
        {"nom": "Mycétome actinomycotique", "categorie": "infectieuse",
         "description": "Infection bactérienne chronique des tissus sous-cutanés", "gravite": "grave"},
        {"nom": "Rhinocéphalite mucormycotique", "categorie": "infectieuse",
         "description": "Infection invasive grave des sinus et du cerveau", "gravite": "grave"},
        {"nom": "Tularémie pneumonique", "categorie": "infectieuse", "description": "Forme pulmonaire de la tularémie",
         "gravite": "grave"},
        {"nom": "Lymphogranulomatose vénérienne", "categorie": "infectieuse",
         "description": "Infection sexuellement transmissible causée par Chlamydia trachomatis", "gravite": "modere"},
        {"nom": "Candidose oesophagienne", "categorie": "infectieuse",
         "description": "Infection fongique de l'œsophage", "gravite": "modere"},
        {"nom": "Toxoplasmose cérébrale", "categorie": "infectieuse",
         "description": "Infection cérébrale grave par Toxoplasma gondii", "gravite": "grave"},
        {"nom": "Strongyloidose chronique asymptomatique", "categorie": "infectieuse",
         "description": "Infection bénigne par Strongyloides stercoralis", "gravite": "leger"},
        {"nom": "Infection à virus Heartland", "categorie": "infectieuse",
         "description": "Maladie virale transmise par les tiques", "gravite": "modere"},
        {"nom": "Fièvre à virus Bourbon", "categorie": "infectieuse",
         "description": "Fièvre virale émergente transmise par les tiques", "gravite": "modere"},
        {"nom": "Dermatophytose des ongles", "categorie": "infectieuse",
         "description": "Infection fongique des ongles (onychomycose)", "gravite": "leger"},
        {"nom": "Infection invasive à Candida", "categorie": "infectieuse",
         "description": "Infection fongique grave affectant le sang ou les organes internes", "gravite": "grave"},
        {"nom": "Blastocystose", "categorie": "infectieuse",
         "description": "Infection intestinale causée par Blastocystis hominis", "gravite": "leger"},
        {"nom": "Bilharziose hépatosplénique", "categorie": "infectieuse",
         "description": "Forme grave de schistosomiase affectant le foie et la rate", "gravite": "grave"},
        {"nom": "Fièvre de Lassa hémorragique", "categorie": "infectieuse",
         "description": "Fièvre hémorragique causée par un arenavirus", "gravite": "grave"},
        {"nom": "Fièvre hémorragique des phlébotomes", "categorie": "infectieuse",
         "description": "Fièvre virale transmise par les phlébotomes", "gravite": "modere"},
        {"nom": "Neurocysticercose", "categorie": "infectieuse",
         "description": "Infection cérébrale par des larves de Taenia solium", "gravite": "grave"},
        {"nom": "Filariose lymphatique chronique", "categorie": "infectieuse",
         "description": "Obstruction lymphatique par Wuchereria bancrofti", "gravite": "grave"},
        {"nom": "Encéphalite virale grave", "categorie": "infectieuse",
         "description": "Inflammation cérébrale due à un virus", "gravite": "grave"},
        {"nom": "Anémie bilharzienne", "categorie": "infectieuse",
         "description": "Anémie causée par une infection chronique à Schistosoma", "gravite": "modere"},
        {"nom": "Endocardite bactérienne", "categorie": "infectieuse",
         "description": "Infection des valves cardiaques par des bactéries", "gravite": "grave"},
        {"nom": "Choriorétinite toxoplasmique", "categorie": "infectieuse",
         "description": "Inflammation de la rétine due à Toxoplasma gondii", "gravite": "grave"},
        {"nom": "Leptospirose ictérique", "categorie": "infectieuse",
         "description": "Forme grave de leptospirose avec jaunisse", "gravite": "grave"},
        {"nom": "Fièvre pappataci", "categorie": "infectieuse",
         "description": "Fièvre virale bénigne transmise par les phlébotomes", "gravite": "leger"},
        {"nom": "Pharyngite streptococcique", "categorie": "infectieuse",
         "description": "Inflammation de la gorge causée par Streptococcus pyogenes", "gravite": "modere"},
        {"nom": "Infection respiratoire syncytiale", "categorie": "infectieuse",
         "description": "Infection virale des voies respiratoires inférieures", "gravite": "modere"},
        {"nom": "Infection par Mycoplasma hominis", "categorie": "infectieuse",
         "description": "Infection bactérienne opportuniste", "gravite": "modere"},
        {"nom": "Infection par Ureaplasma urealyticum", "categorie": "infectieuse",
         "description": "Infection bactérienne affectant les voies urinaires", "gravite": "modere"},
        {"nom": "Chlamydiose oculaire", "categorie": "infectieuse",
         "description": "Infection des yeux causée par Chlamydia trachomatis", "gravite": "modere"}

    ]

    def handle(self, *args, **kwargs):
        created_count = 0
        for disease_data in self.DISEASES:
            disease, created = Maladie.objects.get_or_create(
                nom=disease_data["nom"],
                defaults={
                    "categorie": disease_data["categorie"],
                    "description": disease_data["description"],
                    "gravite": disease_data["gravite"],
                },
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(f"{created_count} maladies ont été enregistrées avec succès.")
        )