# Generated by Django 4.2.14 on 2026-01-31 21:53

import core.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('phone_number', models.CharField(help_text='Enter a valid phone number with country code, e.g., +1234567890', max_length=15, verbose_name='Phone Number')),
                ('relationship', models.CharField(choices=[('FAMILY', 'Family Member'), ('FRIEND', 'Friend'), ('COWORKER', 'Coworker'), ('NEIGHBOR', 'Neighbor'), ('OTHER', 'Other')], max_length=255, verbose_name='Relationship to Patient')),
                ('contact_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('OCCASIONAL', 'Occasional')], max_length=255, verbose_name='Frequency of Contact')),
                ('date_contact', models.DateField(blank=True, null=True, verbose_name='Date of Last Contact')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location of Interaction')),
                ('prevention_measures', models.TextField(blank=True, null=True, verbose_name='Prevention Measures Taken')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('smsdepistage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Case Contact',
                'verbose_name_plural': 'Case Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326)),
                ('geojson', models.JSONField(blank=True, db_index=True, null=True)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qlook_id', models.CharField(db_index=True, default=core.models.qlook, editable=False, max_length=100, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=100, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='+22507070707', max_length=20, null=True)),
                ('nationalite', models.CharField(blank=True, default='00000000', max_length=70, null=True)),
                ('email', models.CharField(blank=True, default='email@sah.com', max_length=70, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='urap/users/5.png', null=True, upload_to='urap/users')),
                ('sortie', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='slug field', null=True, unique=True, verbose_name='slug ')),
                ('notify_by_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('can_edit_employee', 'Can edit employee'), ('can_create_employee', 'Can create employee'), ('can_view_salary', 'can view salary'), ('can_view_employee', 'can view employee')),
            },
        ),
        migrations.CreateModel(
            name='HealthRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('Commune', 'Commune'), ('Village', 'Village'), ('Ville', 'Ville'), ('Quartier', 'Quartier')], db_index=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.districtsanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code_vih', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=225)),
                ('prenoms', models.CharField(db_index=True, max_length=225)),
                ('contact', models.CharField(db_index=True, max_length=225)),
                ('adresse_mail', models.CharField(blank=True, max_length=50, unique=True)),
                ('situation_matrimoniale', models.CharField(choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225)),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('date_naissance', models.DateField(blank=True, db_index=True, null=True)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], db_index=True, max_length=50)),
                ('nationalite', models.CharField(max_length=200)),
                ('ethnie', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('cmu', models.CharField(blank=True, max_length=100, null=True)),
                ('nbr_enfants', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Inconnu', 'Inconnu')], max_length=20, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('employeur', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(blank=True, choices=[('Admis', 'Admis'), ('Sorti', 'Sorti'), ('Gueris-EXEA', 'Gueris-EXEA'), ('Transféré-TRANSF', 'Transféré-TRANSF'), ('SCAM', 'SCAM'), ('EVADE', 'EVADE'), ('DCD', 'DCD'), ('Aucun', 'Aucun')], default='Aucun', max_length=100, null=True)),
                ('urgence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('details', models.JSONField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('view_patient_name', 'Can view patient name'), ('view_dossier_patient', 'Can View dossier patient')),
            },
        ),
        migrations.CreateModel(
            name='PolesRegionaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=225, null=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-virus', max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VIHProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_vih', models.CharField(db_index=True, max_length=100, unique=True)),
                ('site_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('numero_dossier_vih', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif (suivi en cours)'), ('transferred_out', 'Transféré (sortant)'), ('transferred_in', 'Transféré (entrant)'), ('lost', 'Perdu de vue'), ('deceased', 'Décédé'), ('closed', 'Clos (archivé)')], db_index=True, default='active', max_length=20)),
                ('date_diagnostic', models.DateField(blank=True, db_index=True, null=True)),
                ('date_enrolement', models.DateField(blank=True, db_index=True, null=True)),
                ('date_debut_arv', models.DateField(blank=True, db_index=True, null=True)),
                ('date_derniere_visite', models.DateField(blank=True, db_index=True, null=True)),
                ('date_prochaine_visite', models.DateField(blank=True, db_index=True, null=True)),
                ('vih_type', models.CharField(choices=[('hiv1', 'VIH-1'), ('hiv2', 'VIH-2'), ('dual', 'VIH-1/2'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=10)),
                ('oms_stage', models.IntegerField(blank=True, choices=[(1, 'OMS I'), (2, 'OMS II'), (3, 'OMS III'), (4, 'OMS IV')], db_index=True, null=True)),
                ('cd4_baseline', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('charge_virale_baseline', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_bilan_baseline', models.DateField(blank=True, null=True)),
                ('tb_coinfection', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('hbv_coinfection', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('hcv_coinfection', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('regimen_code', models.CharField(blank=True, db_index=True, help_text='Code schéma ARV (ex: TDF/3TC/DTG, AZT/3TC/EFV, etc.)', max_length=80, null=True)),
                ('ligne_traitement', models.CharField(choices=[('first', '1ère ligne'), ('second', '2ème ligne'), ('third', '3ème ligne'), ('unknown', 'Inconnue')], db_index=True, default='unknown', max_length=10)),
                ('adherence_estimee', models.CharField(choices=[('good', 'Bonne'), ('fair', 'Moyenne'), ('poor', 'Mauvaise'), ('unknown', 'Inconnue')], default='unknown', max_length=10)),
                ('grossesse_en_cours', models.BooleanField(default=False)),
                ('allaitement', models.BooleanField(default=False)),
                ('provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('motif_transfert', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vih_profiles_created', to='core.employee')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vih_profile', to='core.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vih_profiles_updated', to='core.employee')),
            ],
            options={
                'verbose_name': 'Dossier VIH',
                'verbose_name_plural': 'Dossiers VIH',
            },
        ),
        migrations.CreateModel(
            name='ServiceSubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=225, null=True)),
                ('icon', models.CharField(blank=True, max_length=225, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subactivities', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='PatientUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAdresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('staydate', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cim', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('urlcim', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('categorie', models.CharField(choices=[('infectieuse', 'Maladies infectieuses'), ('cardiovasculaire', 'Maladies cardiovasculaires'), ('respiratoire', 'Maladies respiratoires'), ('metabolique', 'Maladies métaboliques'), ('neurologique', 'Maladies neurologiques'), ('autoimmune', 'Maladies auto-immunes'), ('cancer', 'Cancers'), ('genetique', 'Maladies génétiques'), ('psychiatrique', 'Maladies psychiatriques'), ('musculosquelettique', 'Maladies musculosquelettiques'), ('dermatologique', 'Maladies dermatologiques'), ('gastrointestinale', 'Maladies gastro-intestinales'), ('urologique', 'Maladies urologiques et rénales'), ('rare', 'Maladies rares'), ('mode_de_vie', 'Maladies liées au mode de vie'), ('autre', 'Autres')], default='autre', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('gravite', models.CharField(choices=[('leger', 'Léger'), ('modere', 'Modéré'), ('grave', 'Grave')], default='leger', max_length=20)),
                ('date_diagnostic', models.DateField(blank=True, null=True)),
                ('traitements', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('medecin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maladies_traitees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='core.patient')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('qlook_id', models.CharField(db_index=True, default=core.models.qlook, editable=False, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=100, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='+22507070707', max_length=20, null=True)),
                ('nationalite', models.CharField(blank=True, default='00000000', max_length=70, null=True)),
                ('email', models.CharField(blank=True, default='email@sah.com', max_length=70, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, default='urap/users/5.png', max_length=100, null=True)),
                ('sortie', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='slug field', null=True, verbose_name='slug ')),
                ('notify_by_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.service', verbose_name='service')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
