# Generated by Django 4.2.14 on 2024-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code_vih',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
