# Generated by Django 4.2.14 on 2024-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localite',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='current_locatiom',
            new_name='current_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
