# Generated by Django 4.2.14 on 2024-10-28 19:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_ethnie_alter_patient_code_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(default=core.models.get_random_code, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_vih',
            field=models.CharField(default=core.models.get_incremental_code, max_length=100, unique=True),
        ),
    ]
