# Generated by Django 4.2.14 on 2025-01-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'permissions': (('view_patient_name', 'Can view patient name'),)},
        ),
    ]
