# Generated by Django 4.2.14 on 2025-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='code_cim',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cmu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
