# Generated by Django 4.2.14 on 2025-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='urgence',
            field=models.BooleanField(default=False),
        ),
    ]
