# Generated by Django 4.2.14 on 2025-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notify_by_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='notify_by_sms',
            field=models.BooleanField(default=False),
        ),
    ]
