# Generated by Django 4.2.14 on 2026-01-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_vihprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vihprofile',
            new_name='core_vihpro_status_75ddd0_idx',
            old_name='core_vihpr_status_...',
        ),
        migrations.RenameIndex(
            model_name='vihprofile',
            new_name='core_vihpro_site_co_ca6e6b_idx',
            old_name='core_vihpr_site_co...',
        ),
        migrations.RenameIndex(
            model_name='vihprofile',
            new_name='core_vihpro_date_de_70af29_idx',
            old_name='core_vihpr_date_de...',
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='adherence_estimee',
            field=models.CharField(choices=[('good', 'Bonne'), ('fair', 'Moyenne'), ('poor', 'Mauvaise'), ('unknown', 'Inconnue')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='hbv_coinfection',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='hcv_coinfection',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='ligne_traitement',
            field=models.CharField(choices=[('first', '1ère ligne'), ('second', '2ème ligne'), ('third', '3ème ligne'), ('unknown', 'Inconnue')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='oms_stage',
            field=models.IntegerField(blank=True, choices=[(1, 'OMS I'), (2, 'OMS II'), (3, 'OMS III'), (4, 'OMS IV')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='regimen_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code schéma ARV (ex: TDF/3TC/DTG, AZT/3TC/EFV, etc.)', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Actif (suivi en cours)'), ('transferred_out', 'Transféré (sortant)'), ('transferred_in', 'Transféré (entrant)'), ('lost', 'Perdu de vue'), ('deceased', 'Décédé'), ('closed', 'Clos (archivé)')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='tb_coinfection',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('unknown', 'Inconnu')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='vihprofile',
            name='vih_type',
            field=models.CharField(choices=[('hiv1', 'VIH-1'), ('hiv2', 'VIH-2'), ('dual', 'VIH-1/2'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=10),
        ),
    ]
