# Generated by Django 4.2.14 on 2024-10-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_code_patient_alter_patient_code_vih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code_vih',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Inconnu', 'Inconnu')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nbr_enfants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
