# Generated by Django 4.2.14 on 2026-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_vihpr_status___core_vihpro_status_75ddd0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=0, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
