# Generated by Django 4.2.14 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_code_vih_alter_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
