# Generated by Django 4.2.14 on 2025-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maladie_code_cim'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='urlcim',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maladie',
            name='code_cim',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
