# Generated by Django 4.2.14 on 2024-12-10 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsanitaire',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
