# Generated by Django 4.2.14 on 2025-01-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smit', '0001_initial'),
        ('core', '0002_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillon_for_consultation', to='smit.consultation'),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='examen_demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen_demandee', to='smit.examen'),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillon_for_patient', to='core.patient'),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.typeechantillon'),
        ),
        migrations.AddField(
            model_name='cathegorieechantillon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.cathegorieechantillon'),
        ),
    ]
