# Generated by Django 4.2.14 on 2025-02-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='agent_collect',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='cathegorie',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='examen_demande',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalcathegorieechantillon',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcathegorieechantillon',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicaltypeechantillon',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='CathegorieEchantillon',
        ),
        migrations.DeleteModel(
            name='Echantillon',
        ),
        migrations.DeleteModel(
            name='HistoricalCathegorieEchantillon',
        ),
        migrations.DeleteModel(
            name='HistoricalTypeEchantillon',
        ),
        migrations.DeleteModel(
            name='TypeEchantillon',
        ),
    ]
