# Generated by Django 4.2.14 on 2025-03-16 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smit', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivierdv', to='smit.suivi'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='cathegorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.cathegoriemolecule'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.cathegoriemolecule'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='molecules',
            field=models.ManyToManyField(to='pharmacy.molecule'),
        ),
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(related_name='commandes', to='pharmacy.articlecommande'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicament'),
        ),
    ]
