# Generated by Django 4.2.14 on 2025-07-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('smit', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivierdv', to='smit.suivi'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.commande'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_stock', to='core.employee'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='core.patient'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacie_stock', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='cathegorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.cathegoriemolecule'),
        ),
        migrations.AddField(
            model_name='medocsprescrits',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.cathegoriemolecule'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='molecules',
            field=models.ManyToManyField(to='pharmacy.molecule'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(related_name='commandes', to='pharmacy.articlecommande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='commande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_article', to='core.employee'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicament'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacie_article', to='pharmacy.pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(check=models.Q(('niveau_critique__gt', 0)), name='niveau_critique_positive'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='pharmacy_mo_type_mo_0ffbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_mouvement'], name='pharmacy_mo_date_mo_810926_idx'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('numero',), name='unique_commande_numero'),
        ),
    ]
