# Generated by Django 4.2.14 on 2024-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicament_date_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('Comprimé', 'Comprimé'), ('Sirop', 'Sirop'), ('Injection', 'Injection'), ('Gélule', 'Gélule'), ('Crème', 'Crème'), ('Pommade', 'Pommade'), ('Suppositoire', 'Suppositoire'), ('Gouttes', 'Gouttes'), ('Patch', 'Patch'), ('Inhalateur', 'Inhalateur'), ('Solution', 'Solution'), ('Suspension', 'Suspension'), ('Poudre', 'Poudre'), ('Spray', 'Spray'), ('Ovule', 'Ovule'), ('Collyre', 'Collyre'), ('Aérosol', 'Aérosol'), ('Élixir', 'Élixir'), ('Baume', 'Baume'), ('Granulé', 'Granulé'), ('Capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
