# Generated by Django 4.2.14 on 2025-05-28 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pharmacy.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement']},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['medication']},
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_article', to='core.employee'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacie_article', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='commande',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='commande',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='medocsprescrits',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.commande'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_stock', to='core.employee'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='pharmacy.fournisseur'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacie_stock', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy'),
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='statut',
            field=models.CharField(choices=[('Commande', 'Commandé'), ('Reçu', 'Reçu'), ('En attente', 'En attente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cathegoriemolecule',
            name='nom',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('Commandé', 'Commandé'), ('Reçu', 'Reçu'), ('En attente', 'En attente')], default='Commandé', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='codebarre',
            field=models.CharField(default=pharmacy.models.generate_unique_code_barre, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Le code-barre doit être composé de 12 chiffres.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unitdosage',
            field=models.CharField(blank=True, choices=[('mg', 'Milligramme (mg)'), ('g', 'Gramme (g)'), ('ml', 'Millilitre (ml)'), ('L', 'Litre (L)'), ('mcg', 'Microgramme (mcg)'), ('UI', 'Unité Internationale (UI)'), ('meq', 'Milliequivalent (mEq)'), ('µL', 'Microlitre (µL)'), ('µg', 'Microgramme (µg)'), ('cm³', 'Centimètre Cube (cm³)'), ('mL/kg', 'Millilitre par kilogramme (mL/kg)'), ('mg/m²', 'Milligramme par mètre carré (mg/m²)'), ('mg/kg', 'Milligramme par kilogramme (mg/kg)'), ('g/L', 'Gramme par litre (g/L)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacy.medicament'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='pharmacy.medicament'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='pharmacy_mo_type_mo_0ffbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_mouvement'], name='pharmacy_mo_date_mo_810926_idx'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('numero',), name='unique_commande_numero'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(check=models.Q(('niveau_critique__gt', 0)), name='niveau_critique_positive'),
        ),
    ]
