# Generated by Django 4.2.14 on 2025-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
