# Generated by Django 4.2.14 on 2025-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_commande_options_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medicaments',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medicaments',
            field=models.ManyToManyField(blank=True, to='pharmacy.medicament'),
        ),
    ]
