# Generated by Django 4.2.14 on 2025-02-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_commande_created_at_alter_commande_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medocsprescrits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=355, null=True, unique=True)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('unitdosage', models.CharField(blank=True, choices=[('mg', 'Milligramme (mg)'), ('g', 'Gramme (g)'), ('ml', 'Millilitre (ml)'), ('L', 'Litre (L)'), ('mcg', 'Microgramme (mcg)'), ('UI', 'Unité Internationale (UI)'), ('meq', 'Milliequivalent (mEq)'), ('µL', 'Microlitre (µL)'), ('µg', 'Microgramme (µg)'), ('cm³', 'Centimètre Cube (cm³)'), ('mL/kg', 'Millilitre par kilogramme (mL/kg)'), ('mg/m²', 'Milligramme par mètre carré (mg/m²)'), ('mg/kg', 'Milligramme par kilogramme (mg/kg)'), ('g/L', 'Gramme par litre (g/L)')], help_text='Ex: 500mg, 20mg/ml', max_length=50, null=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('Comprimé', 'Comprimé'), ('Sirop', 'Sirop'), ('Injection', 'Injection'), ('Gélule', 'Gélule'), ('Crème', 'Crème'), ('Pommade', 'Pommade'), ('Suppositoire', 'Suppositoire'), ('Gouttes', 'Gouttes'), ('Patch', 'Patch'), ('Inhalateur', 'Inhalateur'), ('Solution', 'Solution'), ('Suspension', 'Suspension'), ('Poudre', 'Poudre'), ('Spray', 'Spray'), ('Ovule', 'Ovule'), ('Collyre', 'Collyre'), ('Aérosol', 'Aérosol'), ('Élixir', 'Élixir'), ('Baume', 'Baume'), ('Granulé', 'Granulé'), ('Capsule', 'Capsule')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.fournisseur')),
            ],
        ),
    ]
