# Generated by Django 4.2.14 on 2024-11-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medicament_unitdosage_alter_medicament_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
