# Generated by Django 4.2.14 on 2025-02-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medocsprescrits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medocsprescrits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medocsprescrits',
            name='fournisseur',
        ),
    ]
