# Generated by Django 4.2.14 on 2025-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_medocsprescrits_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('comprime', 'comprime'), ('sirop', 'sirop'), ('injection', 'injection'), ('gelule', 'gelule'), ('creme', 'creme'), ('pommade', 'pommade'), ('suppositoire', 'suppositoire'), ('gouttes', 'gouttes'), ('patch', 'patch'), ('inhalateur', 'inhalateur'), ('solution', 'solution'), ('suspension', 'suspension'), ('poudre', 'poudre'), ('spray', 'spray'), ('ovule', 'ovule'), ('collyre', 'collyre'), ('aérosol', 'aérosol'), ('elixir', 'elixir'), ('baume', 'baume'), ('granulé', 'granulé'), ('capsule', 'capsule')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medocsprescrits',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('comprime', 'comprime'), ('sirop', 'sirop'), ('injection', 'injection'), ('gelule', 'gelule'), ('creme', 'creme'), ('pommade', 'pommade'), ('suppositoire', 'suppositoire'), ('gouttes', 'gouttes'), ('patch', 'patch'), ('inhalateur', 'inhalateur'), ('solution', 'solution'), ('suspension', 'suspension'), ('poudre', 'poudre'), ('spray', 'spray'), ('ovule', 'ovule'), ('collyre', 'collyre'), ('aérosol', 'aérosol'), ('elixir', 'elixir'), ('baume', 'baume'), ('granulé', 'granulé'), ('capsule', 'capsule')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='type',
            field=models.CharField(choices=[('comprime', 'comprime'), ('sirop', 'sirop'), ('injection', 'injection'), ('gelule', 'gelule'), ('creme', 'creme'), ('pommade', 'pommade'), ('suppositoire', 'suppositoire'), ('gouttes', 'gouttes'), ('patch', 'patch'), ('inhalateur', 'inhalateur'), ('solution', 'solution'), ('suspension', 'suspension'), ('poudre', 'poudre'), ('spray', 'spray'), ('ovule', 'ovule'), ('collyre', 'collyre'), ('aérosol', 'aérosol'), ('elixir', 'elixir'), ('baume', 'baume'), ('granulé', 'granulé'), ('capsule', 'capsule')], max_length=255),
        ),
    ]
