# Generated by Django 4.2.14 on 2024-12-09 11:40

import django.core.validators
from django.db import migrations, models
import pharmacy.models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_medicament_unitdosage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockalert',
            old_name='alerté',
            new_name='alerte',
        ),
        migrations.RenameField(
            model_name='stockalert',
            old_name='quantité_actuelle',
            new_name='quantite_actuelle',
        ),
        migrations.AlterField(
            model_name='cathegoriemolecule',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='codebarre',
            field=models.CharField(default=pharmacy.models.generate_unique_code_barre, help_text='Code unique pour le médicament', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Le code-barre doit être composé de 12 chiffres.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='articlecommande',
            constraint=models.UniqueConstraint(fields=('commande', 'medicament'), name='unique_commande_medicament'),
        ),
    ]
