# Generated by Django 4.2.14 on 2025-05-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='examens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smit.paraclinicalexam'),
        ),
    ]
