# Generated by Django 4.2.14 on 2025-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='po',
            field=models.FloatField(blank=True, null=True, verbose_name='Périmètre Ombilicale'),
        ),
    ]
