# Generated by Django 4.2.14 on 2024-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='hospitalised',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
