# Generated by Django 4.2.14 on 2025-07-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='suivi',
        ),
        migrations.RemoveField(
            model_name='historicalechantillon',
            name='suivi',
        ),
    ]
