# Generated by Django 4.2.14 on 2025-02-27 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cancellation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
