# Generated by Django 4.2.14 on 2025-02-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaclinicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Hémogramme', 'Hémogramme'), ('Ionogramme', 'Ionogramme'), ('Bilan hépatique', 'Bilan hépatique'), ('Bilan rénal', 'Bilan rénal'), ('Urines', 'Examen d’urines'), ('CRP', 'CRP'), ('PCT', 'PCT'), ('TP', 'TP'), ('TCA', 'TCA'), ('Glycémie', 'Glycémie'), ('HbA1C', 'HbA1C'), ('Tubage gastrique/Crachats', 'Tubage gastrique/Crachats'), ('LCR', 'LCR'), ('Gazometrie', 'Gazometrie'), ('Marquer Cardiaques', 'Marquer Cardiaques'), ('Selles', 'Selles'), ('CrAg', 'CrAg'), ('TB LAM', 'TB LAM')], max_length=50, verbose_name="Type d'Examen")),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, help_text="Résultats de l'examen en texte.", null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='paraclinical_results/')),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Completed', 'Réalisé'), ('Cancelled', 'Annulé')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalization_exams', to='smit.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraclinical_exams', to='core.patient')),
            ],
        ),
    ]
