# Generated by Django 4.2.14 on 2024-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalizationIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, help_text='Température en degrés Celsius', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Fréquence cardiaque (bpm)', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Fréquence respiratoire (rpm)', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Tension artérielle (ex : 120/80 mmHg)', max_length=20, null=True)),
                ('pain_level', models.IntegerField(blank=True, help_text='Niveau de douleur sur une échelle de 1 à 10', null=True)),
                ('mental_state', models.CharField(blank=True, choices=[('clair', 'Clair'), ('confusion', 'Confusion'), ('somnolent', 'Somnolent')], help_text='État de conscience du patient', max_length=20, null=True)),
                ('treatment_response', models.TextField(blank=True, help_text='Réponse du patient au traitement', null=True)),
                ('side_effects', models.TextField(blank=True, help_text='Effets secondaires observés', null=True)),
                ('compliance', models.BooleanField(default=False, help_text='Observance du traitement')),
                ('electrolytes_balance', models.CharField(blank=True, help_text='Équilibre électrolytique', max_length=50, null=True)),
                ('renal_function', models.CharField(blank=True, help_text='État de la fonction rénale', max_length=50, null=True)),
                ('hepatic_function', models.CharField(blank=True, help_text='État de la fonction hépatique', max_length=50, null=True)),
                ('stable_vitals', models.BooleanField(default=False, help_text='Les signes vitaux sont-ils stables?')),
                ('pain_controlled', models.BooleanField(default=False, help_text='La douleur est-elle contrôlée?')),
                ('functional_ability', models.BooleanField(default=False, help_text='Capacité fonctionnelle atteinte?')),
                ('mental_stability', models.BooleanField(default=False, help_text='État mental stable?')),
                ('follow_up_plan', models.TextField(blank=True, help_text='Plan de suivi post-hospitalisation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
