# Generated by Django 4.2.14 on 2025-07-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0002_remove_echantillon_suivi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='suivi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='echantillon_for_suivi', to='smit.suivi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalechantillon',
            name='suivi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smit.suivi'),
        ),
    ]
