# Generated by Django 4.2.14 on 2025-02-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
        ('smit', '0002_paraclinicalexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParaclinicalExam',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Hémogramme', 'Hémogramme'), ('Ionogramme', 'Ionogramme'), ('Bilan hépatique', 'Bilan hépatique'), ('Bilan rénal', 'Bilan rénal'), ('Urines', 'Examen d’urines'), ('CRP', 'CRP'), ('PCT', 'PCT'), ('TP', 'TP'), ('TCA', 'TCA'), ('Glycémie', 'Glycémie'), ('HbA1C', 'HbA1C'), ('Tubage gastrique/Crachats', 'Tubage gastrique/Crachats'), ('LCR', 'LCR'), ('Gazometrie', 'Gazometrie'), ('Marquer Cardiaques', 'Marquer Cardiaques'), ('Selles', 'Selles'), ('CrAg', 'CrAg'), ('TB LAM', 'TB LAM')], max_length=50, verbose_name="Type d'Examen")),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, help_text="Résultats de l'examen en texte.", null=True)),
                ('result_file', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Completed', 'Réalisé'), ('Cancelled', 'Annulé')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smit.hospitalization')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical paraclinical exam',
                'verbose_name_plural': 'historical paraclinical exams',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
