# Generated by Django 4.2.14 on 2025-07-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('smit', '0002_alter_suivi_examens'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepistageVIH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_analyse', models.CharField(max_length=100, unique=True)),
                ('date_test', models.DateField(auto_now_add=True)),
                ('type_test', models.CharField(choices=[('TROD', 'Test Rapide (TROD)'), ('ELISA', 'ELISA'), ('WESTERN_BLOT', 'Western Blot'), ('PCR', 'PCR')], max_length=20)),
                ('resultat', models.CharField(choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INDETERMINE', 'Indéterminé')], max_length=15)),
                ('test_confirmation', models.BooleanField(default=False)),
                ('resultat_confirmation', models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('INDETERMINE', 'Indéterminé')], max_length=15, null=True)),
                ('statut_patient', models.CharField(choices=[('NOUVEAU', 'Nouveau patient'), ('CONNU', 'Déjà connu séropositif')], max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depistages', to='core.patient')),
            ],
            options={
                'verbose_name': 'Test de dépistage VIH',
                'verbose_name_plural': 'Dépistages VIH',
                'ordering': ['-date_test'],
            },
        ),
        migrations.CreateModel(
            name='BilanInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('emergency', 'Urgence')], default='medium', max_length=20, verbose_name='Priorité')),
                ('description', models.TextField(help_text="Détails cliniques pertinents pour l'examen", verbose_name="Description de l'examen")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires médicaux')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='bilans/reports/%Y/%m/%d/', verbose_name="Rapport d'examen")),
                ('is_critical', models.BooleanField(default=False, verbose_name='Résultat critique?')),
                ('antecedents_medicaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_init_antecedents', to='smit.antecedentsmedicaux')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_init_doc', to='core.employee', verbose_name='Médecin prescripteur')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smit.examenstandard', verbose_name='Examen demandé')),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_init_hospi', to='smit.hospitalization', verbose_name='Hospitalisation associée')),
                ('infection_opportuniste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_init_infection_oppo', to='smit.infectionopportuniste')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_init_patient', to='core.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Bilan initial VIH',
                'verbose_name_plural': 'Bilans initiaux VIH',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='smit_bilani_status_5fe18b_idx'), models.Index(fields=['priority'], name='smit_bilani_priorit_d5c8ed_idx'), models.Index(fields=['is_critical'], name='smit_bilani_is_crit_e0b380_idx')],
            },
        ),
    ]
