# Generated by Django 4.2.14 on 2024-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0002_alter_consultation_hospitalised'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='motifrejet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
