# Generated by Django 4.2.14 on 2025-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0002_historicalappareil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemepose',
            options={'ordering': ['-created_at'], 'verbose_name': "problème posé lors de l'hospitalisation"},
        ),
        migrations.AddField(
            model_name='imageriemedicale',
            name='interpretation_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Interprétation IA'),
        ),
    ]
