# Generated by Django 4.2.14 on 2024-10-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0002_hospitalizationindicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalizationindicators',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_autres', to='smit.hospitalization'),
        ),
    ]
