# Generated by Django 4.2.14 on 2025-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0002_prescription_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
