# Generated by Django 4.2.14 on 2025-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_alter_problemepose_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageriemedicale',
            name='organes_detectes',
            field=models.TextField(blank=True, null=True, verbose_name='Organes détectés'),
        ),
    ]
