# Generated by Django 4.2.14 on 2025-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_historicalparaclinicalexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparaclinicalexam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="nom de l'Examen"),
        ),
        migrations.AddField(
            model_name='paraclinicalexam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="nom de l'Examen"),
        ),
    ]
