# Generated by Django 4.2.14 on 2025-02-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('smit', '0003_alter_prescription_cancellation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cancellation_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_cancelled_by', to='core.employee'),
        ),
    ]
