# Generated by Django 4.2.14 on 2025-07-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_echantillon_suivi_historicalechantillon_suivi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='historicalechantillon',
            name='expiration_date',
        ),
    ]
