# Generated by Django 4.2.14 on 2025-07-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_depistagevih_bilaninitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanparaclinique',
            name='is_initial_vih',
            field=models.BooleanField(default=False, verbose_name='Fait partie du bilan initial VIH/SIDA ?'),
        ),
    ]
