# Generated by Django 4.2.14 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_hospitalizationindicators_hospitalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lithospitalisation',
            name='is_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lithospitalisation',
            name='is_out_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lithospitalisation',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
