# Generated by Django 4.2.14 on 2024-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0003_consultation_motifrejet'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
