# Generated by Django 4.2.14 on 2025-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0004_bilanparaclinique_is_initial_vih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilaninitial',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='bilaninitial',
            name='infection_opportuniste',
        ),
        migrations.AddField(
            model_name='bilaninitial',
            name='examens',
            field=models.ManyToManyField(blank=True, related_name='bilans_init_examens', to='smit.examenstandard', verbose_name='Examens demandés'),
        ),
        migrations.AddField(
            model_name='bilaninitial',
            name='infections_opportunistes',
            field=models.ManyToManyField(blank=True, related_name='bilans_init_infection_oppo', to='smit.infectionopportuniste', verbose_name='Infections opportunistes'),
        ),
        migrations.RemoveField(
            model_name='bilaninitial',
            name='antecedents_medicaux',
        ),
        migrations.AddField(
            model_name='bilaninitial',
            name='antecedents_medicaux',
            field=models.ManyToManyField(blank=True, related_name='bilans_init_antecedents', to='smit.antecedentsmedicaux', verbose_name='Antécédents médicaux'),
        ),
    ]
