# Generated by Django 4.2.14 on 2025-07-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0004_remove_echantillon_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='status_echantillons',
            field=models.CharField(choices=[('Demande', 'Demande'), ('Validé', 'Validé'), ('Annulé', 'Annulé'), ('Prélevé', 'Prélevé')], default='Demande', max_length=20, verbose_name="Statut de l'échantillon"),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echantillon_for_suivi', to='smit.suivi'),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='status_echantillons',
            field=models.CharField(choices=[('Demande', 'Demande'), ('Validé', 'Validé'), ('Annulé', 'Annulé'), ('Prélevé', 'Prélevé')], default='Demande', max_length=20, verbose_name="Statut de l'échantillon"),
        ),
    ]
