# Generated by Django 4.2.14 on 2024-08-14 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_status'),
        ('smit', '0004_alter_hospitalization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaladieOpportuniste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnqueteVih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prophylaxie_antiretrovirale', models.BooleanField(default=False)),
                ('prophylaxie_type', models.CharField(blank=True, max_length=255, null=True)),
                ('traitement_antiretrovirale', models.BooleanField(default=False)),
                ('traitement_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dernier_regime_antiretrovirale', models.BooleanField(default=False)),
                ('dernier_regime_antiretrovirale_type', models.CharField(blank=True, max_length=255, null=True)),
                ('traitement_prophylactique_cotrimoxazole', models.BooleanField(default=False)),
                ('evolutif_cdc_1993', models.CharField(blank=True, choices=[('Adulte Stade A', 'Adulte Stade A'), ('Adulte Stade B', 'Adulte Stade B'), ('Adulte Stade C', 'Adulte Stade C'), ('Enfant Stade N', 'Enfant Stade N'), ('Enfant Stade A', 'Enfant Stade A'), ('Enfant Stade B', 'Enfant Stade B'), ('Enfant Stade C', 'Enfant Stade C')], max_length=255, null=True)),
                ('sous_traitement', models.BooleanField(default=False)),
                ('score_karnofsky', models.IntegerField(blank=True, null=True)),
                ('descriptif', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antecedents', models.ManyToManyField(related_name='antecedents_vih', to='smit.maladieopportuniste')),
                ('infection_opportuniste', models.ManyToManyField(related_name='infection_opportuniste', to='smit.maladieopportuniste')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
