# Generated by Django 4.2.14 on 2024-08-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('smit', '0004_consultation_requested_at_consultation_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lithospitalisation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
    ]
