# Generated by Django 4.2.14 on 2025-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0004_imageriemedicale_organes_detectes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageriemedicale',
            name='anomalies_detectees',
            field=models.TextField(blank=True, null=True, verbose_name='Anomalies détectées'),
        ),
    ]
