# Generated by Django 4.2.14 on 2024-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0004_lithospitalisation_is_cleaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lithospitalisation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
