# Generated by Django 4.2.14 on 2024-10-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0005_lithospitalisation_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='lithospitalisation',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
