# Generated by Django 4.2.14 on 2024-08-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_status'),
        ('smit', '0005_maladieopportuniste_enquetevih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquetevih',
            name='date_debut',
        ),
        migrations.AlterField(
            model_name='enquetevih',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquetevihs', to='core.patient'),
        ),
    ]
