# Generated by Django 4.2.14 on 2025-07-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0005_alter_echantillon_status_echantillons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='examen_demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen_demandee', to='smit.examenstandard'),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='examen_demande',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smit.examenstandard'),
        ),
    ]
