# Generated by Django 4.2.14 on 2025-07-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smit', '0006_bilaninitial_reference_range_bilaninitial_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilaninitial',
            name='description',
            field=models.TextField(verbose_name="Description de l'examen"),
        ),
        migrations.AlterField(
            model_name='bilaninitial',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='Résultat critique ?'),
        ),
        migrations.AlterField(
            model_name='bilaninitial',
            name='result',
            field=models.JSONField(blank=True, null=True, verbose_name='Résultats'),
        ),
        migrations.CreateModel(
            name='HistoricalBilanInitial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('emergency', 'Urgence')], default='medium', max_length=20, verbose_name='Priorité')),
                ('description', models.TextField(verbose_name="Description de l'examen")),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Résultats')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du résultat')),
                ('reference_range', models.CharField(blank=True, max_length=250, null=True, verbose_name='Valeurs de référence')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unité de mesure')),
                ('report_file', models.TextField(blank=True, max_length=100, null=True, verbose_name="Rapport d'examen")),
                ('is_critical', models.BooleanField(default=False, verbose_name='Résultat critique ?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de mise à jour')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires médicaux')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.employee', verbose_name='Médecin prescripteur')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smit.hospitalization', verbose_name='Hospitalisation associée')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'historical Bilan initial VIH',
                'verbose_name_plural': 'historical Bilans initiaux VIH',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
