# Generated by Django 4.2.14 on 2025-07-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0006_alter_echantillon_examen_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='commentaire_resultat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalechantillon',
            name='commentaire_resultat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalechantillon',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
