# Generated by Django 4.2.14 on 2025-02-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0006_historicalparaclinicalexam_iteration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='lit_hospy', to='smit.lithospitalisation'),
            preserve_default=False,
        ),
    ]
