# Generated by Django 4.2.14 on 2024-08-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0006_remove_enquetevih_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquetevih',
            name='conultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enqueteconsultation', to='smit.consultation'),
        ),
    ]
