# Generated by Django 4.2.14 on 2024-10-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0006_lithospitalisation_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lit_hospy', to='smit.lithospitalisation'),
        ),
    ]
