# Generated by Django 4.2.14 on 2024-08-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0007_enquetevih_conultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquetevih',
            old_name='conultation',
            new_name='consultation',
        ),
    ]
