# Generated by Django 4.2.14 on 2025-07-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0007_alter_bilaninitial_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilaninitial',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilanconsultation', to='smit.consultation'),
        ),
        migrations.AddField(
            model_name='historicalbilaninitial',
            name='consultation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smit.consultation'),
        ),
        migrations.AlterField(
            model_name='bilaninitial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé'), ('suivi', 'En Suivi')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalbilaninitial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé'), ('suivi', 'En Suivi')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
