# Generated by Django 4.2.14 on 2024-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0007_alter_hospitalization_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='posology',
            field=models.CharField(blank=True, choices=[('Une fois par jour', 'Une fois par jour'), ('Deux fois par jour', 'Deux fois par jour'), ('Trois fois par jour', 'Trois fois par jour'), ('Quatre fois par jour', 'Quatre fois par jour'), ('Toutes les 4 heures', 'Toutes les 4 heures'), ('Toutes les 6 heures', 'Toutes les 6 heures'), ('Toutes les 8 heures', 'Toutes les 8 heures'), ('Si besoin', 'Si besoin'), ('Avant les repas', 'Avant les repas'), ('Après les repas', 'Après les repas'), ('Au coucher', 'Au coucher'), ('Une fois par semaine', 'Une fois par semaine'), ('Deux fois par semaine', 'Deux fois par semaine'), ('Un jour sur deux', 'Un jour sur deux')], max_length=350, null=True),
        ),
    ]
