# Generated by Django 4.2.14 on 2024-11-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0008_prescription_posology'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospiprescriptions', to='smit.hospitalization'),
        ),
    ]
