# Generated by Django 4.2.14 on 2025-07-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0008_bilaninitial_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='bilan_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='smit.bilaninitial', verbose_name='Bilan Initial associé'),
        ),
        migrations.AlterField(
            model_name='bilaninitial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé'), ('En Suivi', 'En Suivi')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalbilaninitial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('canceled', 'Annulé'), ('En Suivi', 'En Suivi')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
