# Generated by Django 4.2.14 on 2024-11-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0009_prescription_hospitalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicationsIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chlorure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phosphate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bun', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bilirubine_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('albumine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_compliques', to='smit.hospitalization')),
            ],
        ),
    ]
