# Generated by Django 4.2.14 on 2025-07-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0009_suivi_bilan_initial_alter_bilaninitial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='rdvconsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suiviconsultation', to='smit.consultation', verbose_name='Rendez-vous en pharmacie'),
        ),
    ]
