# Generated by Django 4.2.14 on 2025-02-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0009_cathegorieechantillon_typeechantillon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentsservice', to='core.service'),
        ),
    ]
