# Generated by Django 4.2.14 on 2025-02-15 17:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0010_alter_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquemaladie',
            name='antecedents',
        ),
        migrations.RemoveField(
            model_name='historiquemaladie',
            name='diagnostics_associes',
        ),
        migrations.RemoveField(
            model_name='historiquemaladie',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='historiquemaladie',
            name='traitements_precedents',
        ),
        migrations.AddField(
            model_name='typeantecedent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smit.typeantecedent'),
        ),
        migrations.AlterField(
            model_name='historiquemaladie',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
