# Generated by Django 4.2.14 on 2024-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0010_complicationsindicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='Périmètre Braciale'),
        ),
    ]
