# Generated by Django 4.2.14 on 2025-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0010_suivi_rdvconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='difficultes_psychosociales',
            field=models.TextField(blank=True, null=True, verbose_name='Difficultés psychosociales identifiées'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='effets_secondaires',
            field=models.TextField(blank=True, null=True, verbose_name='Effets secondaires rapportés'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='presence_io',
            field=models.BooleanField(default=False, verbose_name='Infection opportuniste présente'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='prophylaxie_cotrimoxazole',
            field=models.BooleanField(default=False, verbose_name='Prophylaxie cotrimoxazole'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='soutien_familial',
            field=models.CharField(blank=True, choices=[('bon', 'Bon'), ('modere', 'Modéré'), ('faible', 'Faible'), ('absent', 'Absent')], max_length=20, null=True, verbose_name='Soutien familial'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='stade_oms',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stade 1'), (2, 'Stade 2'), (3, 'Stade 3'), (4, 'Stade 4')], null=True, verbose_name='Stade OMS'),
        ),
    ]
