# Generated by Django 4.2.14 on 2025-07-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0011_suivi_difficultes_psychosociales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='recommandations_auto',
            field=models.TextField(blank=True, null=True, verbose_name='Recommandations automatiques'),
        ),
    ]
