# Generated by Django 4.2.14 on 2024-12-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_polesregionaux_remove_location_commune_and_more'),
        ('smit', '0011_constante_pb'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_prescriptions', to='core.employee'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='observations',
            field=models.TextField(blank=True, help_text="Notes ou observations lors de l'exécution.", null=True),
        ),
    ]
