# Generated by Django 4.2.14 on 2025-02-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0011_remove_historiquemaladie_antecedents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeantecedent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_types', to='smit.typeantecedent'),
        ),
    ]
