# Generated by Django 4.2.14 on 2025-02-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0012_alter_typeantecedent_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDeVieCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeDeVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Détails sur le mode de vie', null=True)),
                ('frequence', models.CharField(blank=True, choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('occasionnel', 'Occasionnel'), ('rare', 'Rare')], max_length=100, null=True)),
                ('niveau_impact', models.CharField(blank=True, choices=[('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé')], help_text='Impact sur la santé', max_length=50, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_de_vie', to='smit.modedeviecategorie')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospimodedevie', to='smit.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_de_vie', to='core.patient')),
            ],
        ),
    ]
