# Generated by Django 4.2.14 on 2025-07-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0012_suivi_recommandations_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocole',
            name='frequence',
            field=models.CharField(choices=[('Mensuel', 'Mensuel'), ('Bimestriel', 'Bimestriel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel')], default='Mensuel', max_length=50, verbose_name='Fréquence de suivi pharmacie'),
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('APPEL', 'Appel téléphonique')], max_length=50)),
                ('message', models.TextField()),
                ('frequence', models.CharField(choices=[('PONCTUEL', 'Ponctuel'), ('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('protocole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smit.protocole')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SURVEILLANCE', 'Surveillance médicale'), ('COUNSELING', 'Counseling'), ('DEPISTAGE', 'Dépistage'), ('NUTRITION', 'Support nutritionnel')], max_length=50)),
                ('description', models.TextField()),
                ('date_prevue', models.DateField()),
                ('frequence', models.CharField(choices=[('PONCTUEL', 'Ponctuel'), ('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('protocole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smit.protocole')),
            ],
        ),
    ]
