# Generated by Django 4.2.14 on 2024-12-08 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_polesregionaux_remove_location_commune_and_more'),
        ('smit', '0012_prescription_executed_at_prescription_executed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Taken', 'Taken'), ('Missed', 'Missed')], default='Pending', max_length=50)),
                ('observations', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_meds', to='core.employee')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='smit.prescription')),
            ],
        ),
    ]
