# Generated by Django 4.2.14 on 2024-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0013_prescriptionexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pendant',
            field=models.CharField(blank=True, choices=[('1', '1 jour'), ('2', '2 jour'), ('3', '3 jour'), ('4', '4 jour')], max_length=350, null=True),
        ),
    ]
