# Generated by Django 4.2.14 on 2025-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0013_modedeviecategorie_modedevie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modedevie',
            name='niveau_impact',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé')], help_text='Impact sur la santé', max_length=50, null=True),
        ),
    ]
