# Generated by Django 4.2.14 on 2025-07-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0013_protocole_frequence_rappel_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suiviprotocole',
            unique_together={('protocole', 'suivi')},
        ),
    ]
