# Generated by Django 4.2.14 on 2025-02-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0014_alter_modedevie_niveau_impact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modedevie',
            old_name='date_enregistrement',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='modedevie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_vie_creator', to='core.employee'),
        ),
        migrations.AddField(
            model_name='modedevie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modedevie',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_de_vie_patients', to='core.patient'),
        ),
    ]
