# Generated by Django 4.2.14 on 2024-12-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0014_prescription_pendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='a_partir_de',
            field=models.CharField(blank=True, choices=[('1', '1 heure'), ('2', '2 heures'), ('3', '3 heures'), ('4', '4 heures')], max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pendant',
            field=models.CharField(blank=True, choices=[('1', '1 jour'), ('2', '2 jours'), ('3', '3 jours'), ('4', '4 jours'), ('5', '5 jours'), ('7', '1 semaine'), ('14', '2 semaines'), ('21', '3 semaines'), ('30', '1 mois')], max_length=350, null=True),
        ),
    ]
