# Generated by Django 4.2.14 on 2025-02-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0015_rename_date_enregistrement_modedevie_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_types_appareil', to='smit.appareiltype')),
            ],
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('etat', models.CharField(choices=[('normal', 'Normal'), ('altéré', 'Altéré'), ('anormal', 'Anormal'), ('non-applicable', 'non-applicable')], default='normal', max_length=50)),
                ('observation', models.TextField(help_text="Détails de l'examen clinique de l'organe")),
                ('type_appareil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smit.appareiltype')),
            ],
        ),
    ]
