# Generated by Django 4.2.14 on 2024-12-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0015_prescription_a_partir_de_alter_prescription_pendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='a_partir_de',
            field=models.CharField(blank=True, choices=[('1', '1 heure'), ('2', '2 heures'), ('3', '3 heures'), ('4', '4 heures'), ('6', '6 heures'), ('8', '8 heures'), ('12', '12 heures'), ('24', '24 heures'), ('48', '48 heures'), ('72', '72 heures')], max_length=350, null=True),
        ),
    ]
