# Generated by Django 4.2.14 on 2025-02-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0016_appareiltype_appareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens_appareils', to='smit.hospitalization'),
        ),
    ]
