# Generated by Django 4.2.14 on 2025-02-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0017_appareil_hospitalisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='appareil',
            unique_together={('hospitalisation', 'nom')},
        ),
    ]
