# Generated by Django 4.2.14 on 2025-02-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smit', '0018_alter_appareil_nom_alter_appareil_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appareil',
            unique_together=set(),
        ),
    ]
