# Generated by Django 4.2.14 on 2025-02-16 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0019_alter_appareil_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appareil',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appareil_control_creator', to='core.employee'),
        ),
        migrations.AddField(
            model_name='appareil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
