# Generated by Django 4.2.14 on 2025-02-16 00:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0020_appareil_created_at_appareil_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSyndromique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumer_reccorder', to='core.employee')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_maladie_hospi', to='smit.hospitalization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_resume_syndromique', to='core.patient')),
            ],
            options={
                'verbose_name': 'resume syndromique de la Maladie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemePose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probleme_creator', to='core.employee')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probleme_maladie_hospi', to='smit.hospitalization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_maladie_probleme', to='core.patient')),
            ],
            options={
                'verbose_name': 'resume syndromique de la Maladie',
                'ordering': ['-created_at'],
            },
        ),
    ]
