# Generated by Django 4.2.14 on 2025-02-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0021_resumesyndromique_problemepose'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBilanParaclinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name='Nom du type de bilan')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name="Nom de l'examen")),
                ('type_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smit.typebilanparaclinique', verbose_name="Type d'examen")),
            ],
        ),
        migrations.CreateModel(
            name='BilanParaclinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'examen")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('result', models.CharField(blank=True, max_length=250, null=True, verbose_name='Résultat')),
                ('result_date', models.DateTimeField(verbose_name='Date du résultat')),
                ('reference_range', models.CharField(blank=True, max_length=250, null=True, verbose_name='Valeur de référence')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unité de mesure')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire du médecin')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name="Statut de l'examen")),
                ('report_file', models.FileField(blank=True, null=True, upload_to='bilans/', verbose_name='Fichier du rapport')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_medecin', to='core.employee', verbose_name='Médecin prescripteur')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smit.examenstandard', verbose_name='Examen demandé')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='smit.hospitalization', verbose_name='hospitalisation_bilan_paraclinique')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='core.patient', verbose_name='bilanparacliniquepatient')),
            ],
        ),
    ]
