# Generated by Django 4.2.14 on 2025-02-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_user'),
        ('smit', '0022_typebilanparaclinique_examenstandard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanparaclinique',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='smit.hospitalization', verbose_name='hospitalisation_bilan_paraclinique'),
        ),
        migrations.AlterField(
            model_name='bilanparaclinique',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='core.patient', verbose_name='bilanparacliniquepatient'),
        ),
        migrations.AlterField(
            model_name='bilanparaclinique',
            name='result_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du résultat'),
        ),
    ]
