# Generated by Django 4.2.14 on 2025-02-17 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_patient_user'),
        ('smit', '0023_alter_bilanparaclinique_hospitalisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeImagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name="Type d'imagerie")),
            ],
        ),
        migrations.CreateModel(
            name='ImagerieMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Motif de la demande')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='imagerie/images/', verbose_name="Fichier d'imagerie")),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='imagerie/dicom/', verbose_name='Fichier DICOM')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Interprétation du radiologue')),
                ('rapport_file', models.FileField(blank=True, null=True, upload_to='imagerie/rapports/', verbose_name='Fichier du rapport')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours d’analyse'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name="Statut de l'examen")),
                ('date_examen', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'examen")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagerieshospi', to='smit.hospitalization', verbose_name='Hospitalisation')),
                ('medecin_prescripteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_imagerie', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageriespatient', to='core.patient', verbose_name='Patient')),
                ('radiologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiologue', to=settings.AUTH_USER_MODEL, verbose_name='Radiologue')),
                ('type_imagerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smit.typeimagerie', verbose_name="Type d'imagerie")),
            ],
        ),
    ]
